services:
  webapp:
    build: ./
    container_name: hypermanager
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SERVICE_BACKLOG=${SERVICE_BACKLOG}
      - SERVICE_ASSIST=${SERVICE_ASSIST}
      - SERVICE_ATTACHMENT=${SERVICE_ATTACHMENT}
      - API_KEY=${API_KEY}

